apiVersion: v1
kind: Secret
metadata:
  namespace: crossplane-system
  name: provider-os-secret
type: Opaque
data:
  token: BASE64ENCODED_PROVIDER_CREDS
---
apiVersion: os.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: example
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: provider-os-secret
      key: token
  identityEndpoint: "https://my-openstack.com:5000/v3.0"
  projectID: PROJECT_ID
  userName: admin
